### ISSUE TITLE
[page-module] Being able to copy pages

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4808] opened 2018-06-28 17:42 UTC
This is a request that could be a duplicate. I know others have asked. I know it has been talked about. Tried searching for duplicate and copy but didn't find requests in here for it. So i thought id add it.

**Describe the solution you'd like**
I would like to be able to duplicate a page / stream with the fields and values within it. As an example say a page with a couple of grids within it. I want to be able to click copy/duplicate and then i have a copy of it.

**Additional context**
I know this is not something that will be in there tomorrow most likely. But at some point i think it is a feature our beloved cms should have!

**Comment by edster** [comment] 2019-01-15 23:44
I have an extension for pages and posts that does this you can purchase.

**Comment by RyanThompson** [comment] 2019-01-18 03:38
Duplicate of https://github.com/pyrocms/pyrocms/issues/4628

**Closed as completed by RyanThompson** 2019-01-18 03:38 UTC
Labels: Type: Feature Request, Status: Review Needed
