### ISSUE TITLE
[field_types] Adding Class

### ISSUE THREAD

**Issue by jcastillotx** [pyrocms/pyrocms#4100] opened 2017-01-31 04:14 UTC
It would be to be able to add a class to the field type so we can use bootstrap columns.

**Comment by Piterden** [comment] 2017-01-31 10:44
1. Which field type exactly?
2. I suppose you mean HTML-class? If so, you need to accurate to which element you need to add class.

**Comment by RyanThompson** [comment] 2017-02-01 05:32
This is something that is going into the `sections` definition.

**Comment by RyanThompson** [comment] 2017-02-01 05:33
Technically duplicate of: https://github.com/pyrocms/pyrocms/issues/3980

**Closed by RyanThompson** 2017-02-01 05:33 UTC

**Comment by RyanThompson** [comment] 2017-02-01 06:49
Check this out: https://github.com/anomalylabs/streams-platform/commit/a22c50278a7dc58a96b15f524b7f0d218c07b07e
