### ISSUE TITLE
Configuration caching throws fatal error: "undefined method Closure::__set_state()"

### ISSUE THREAD

**Issue by TheBeems** [pyrocms/pyrocms#4551] opened 2017-08-29 17:40 UTC
## Steps to reproduce
I installed a clean website with `pyro new website.dev` and went through the install. 
When installation was finished I issued the command `php artisan config:cache` where it compiles the configuration to config.php in `/bootstrap/cache/`. 

But after that the website gives a fatal error and the artisan command won't work in the CLI:
```php
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Closure::__set_state() in /home/vagrant/Code/bootstrap/cache/config.php:1964
Stack trace:
PHP 0 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(27): require()
PHP 1 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap(Object(Illuminate\Foundation\Application))
PHP 2 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
PHP 3 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(113): Illuminate\Foundation\Console\Kernel->bootstrap()
PHP 4 /home/vagrant/Code/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
PHP 5 {main}
  thrown in /home/vagrant/Code/bootstrap/cache/config.php on line 1964
```
After deleting the `config.php` from the `/bootstrap/cache` directory, all is fine again.

The part inside the `config.php` that erred is as follows:

```php
array (
      'env' => 'DATE_FORMAT',
      'bind' => 'streams::datetime.date_format',
      'type' => 'anomaly.field_type.select',
      'placeholder' => false,
      'required' => true,
      'config' => 
      array (
        'options' => 
        array (
          'j F, Y' => 
          Closure::__set_state(array(
          )),
          'j M, y' => 
          Closure::__set_state(array(
          )),
          'm/d/Y' => 
          Closure::__set_state(array(
          )),
          'd/m/Y' => 
          Closure::__set_state(array(
          )),
          'Y-m-d' => 
          Closure::__set_state(array(
          )),
        ),
      ),
    ),
```
## Why it errors
It is because there have been fuctions used inside the config of the streams-platform. The above code can be located in https://github.com/anomalylabs/streams-platform/blob/1.2/resources/config/preferences/preferences.php 

I tracked this issue down to http://www.laravel-auditing.com/docs/4.1/troubleshooting where it states that 
> To overcome this, the resolver should be set as a FQCN instead.

## Solution?
According to the resolver documentation http://www.laravel-auditing.com/docs/4.1/general-settings it should be used like:
```php
return [
    'user' = [
        'resolver' => App\User::class,
    ],
];
```

I just started with PHP and PyroCMS and lack the know-how to fix something like this and if it is even fixable in PyroCMS. Would be nice if it could be fixed so that we can use `artisan config:cache` without errors.

Thank you!

**Comment by Piterden** [comment] 2017-08-30 01:06
`App\User::class` is just the string `'App\User'`
PyroCMS 3.* works on top of Laravel 5.\*, so v4.\* instructions could have much differences.

Why do you need to cache your config? Is that necessary? What are you trying to achieve with this?

Btw, this works well, but there are another files with closures.
```php
<?php

return [
    'per_page'    => [
        'env'      => 'RESULTS_PER_PAGE',
        'bind'     => 'streams::system.per_page',
        'type'     => 'anomaly.field_type.integer',
        'required' => true,
        'config'   => [
            'default_value' => 15,
            'min'           => 5,
        ],
    ],
    'timezone'    => [
        'env'    => 'APP_TIMEZONE',
        'bind'   => 'app.timezone',
        'type'   => 'anomaly.field_type.select',
        'config' => [
            'handler'       => 'timezones',
            'default_value' => config('app.timezone'),
        ],
    ],
    'date_format' => [
        'env'         => 'DATE_FORMAT',
        'bind'        => 'streams::datetime.date_format',
        'type'        => 'anomaly.field_type.select',
        'placeholder' => false,
        'required'    => true,
        'config'      => [
            'options' => [
                'j F, Y' => date('j F, Y'), // 10 July, 2015
                'j M, y' => date('j M, y'), // 10 Jul, 15
                'm/d/Y'  => date('m/d/Y'), // 07/10/2015
                'd/m/Y'  => date('d/m/Y'), // 10/07/2015
                'Y-m-d'  => date('Y-m-d'), // 2015-07-10
            ],
        ],
    ],
    'time_format' => [
        'env'         => 'TIME_FORMAT',
        'bind'        => 'streams::datetime.time_format',
        'type'        => 'anomaly.field_type.select',
        'placeholder' => false,
        'required'    => true,
        'config'      => [
            'options' => [
                'g:i A' => date('g:i A'), // 4:00 PM
                'g:i a' => date('g:i a'), // 4:00 pm
                'H:i'   => date('H:i'), // 16:00
            ],
        ],
    ],
];
```
@agustindidiego did you make a fix for this?

**Comment by TheBeems** [comment] 2017-09-01 23:22
> Why do you need to cache your config? Is that necessary? What are you trying to achieve with this?

Despite if I need it or not, it is an feature of Laravel to cache your config. PyroCMS advertises itself as 
'_a natural extension of Laravel_' and to '_embrace it everywhere_'. 

The `date()` works, the other Closures are more difficult to fix.

**Comment by Piterden** [comment] 2017-09-02 05:32
The biggest fuckup is the difference between behaviours of closures and strict getters. For example config resolves different values.

**Comment by RyanThompson** [comment] 2017-09-06 16:09
@TheBeems @Piterden has been working on removing closures so we can cache config - will merge and get this sorted soon

**Comment by Piterden** [comment] 2017-09-06 17:37
Actually I had done all, excepting the main config of streams-platform. @RyanThompson help me with it, I had been stuck there.

**Comment by machii28** [comment] 2017-10-08 03:31
Any update with this one ?

**Comment by Piterden** [comment] 2017-10-09 15:47
Some PRs to core had been merged. What code says?

**Comment by Pixney-William** [comment] 2018-06-28 16:44
Do you have any information on this task @Piterden , is it still in progress or has it been completed?

**Comment by mmodler** [comment] 2018-09-13 06:48
Today i tried config caching - not working due to closures.

Any news on this topic? Thanks!

**Comment by ultrono** [comment] 2018-12-05 21:24
@RyanThompson Is there any news on this? 

I'm working on a deployment script and caching the config is a standard thing anyone deploying live Laravel applications will )or should) be doing. 

To recover after running `php artisan config:cache` on a new install of v3.5 I needed to delete bootstrap/cache/config.php and then run `composer dump-autoload` - which isn't ideal 😃  

In some of bigger Laravel application configuration caching has helped with boot times.

IMO this should be documented somewhere, as `config:cache` is a standard Laravel command that they specifically advise using for live applications - https://laravel.com/docs/5.7/configuration#configuration-caching. 🤔

**Comment by drmonkeyninja** [comment] 2019-01-11 09:21
I've just had the same issue. As @ultrono says Laravel recommend caching the config so this wants to work with Pyro.

**Comment by RyanThompson** [comment] 2019-03-03 09:24
Duplicate of which is scheduled for 3.7 https://github.com/pyrocms/pyrocms/issues/4883

**Closed as completed** 2019-03-03 09:24 UTC
Labels: Bug, Status: In Progress, Type: Follow up
